#!/bin/bash

DIR="$HOME/Screenshots"
mkdir -p "$DIR"
FILE="$DIR/$(date +%Y-%m-%d_%H-%M-%S).png"

if [[ "$1" = "-f" ]]; then
    grim "$FILE"
else
    grim -g "$(slurp -d -b 6c708640 -c d1d7e8ff -w 0)" "$FILE"
fi
wl-copy < "$FILE"
