#!/bin/bash
file="$1"
name="${file%.*}"
[[ -z "$file" || ! -f "$file" ]] && exit 1

ffmpeg -i "$file" \
       -vf "scale=2560:1440:force_original_aspect_ratio=decrease,pad=2560:1440:(ow-iw)/2:(oh-ih)/2:black" \
       -frames:v 1 \
       "${name}.png" && rm -f "$file"
