#!/bin/bash

dir="$HOME/Wallpapers/"
if [[ ! -d "$dir" ]]; then
  echo "Ошибка: директория '$dir' не существует"
  exit 1
fi


fzf_args=(
  --multi
  --preview "magick $HOME/Wallpapers/{} -resize 800x600 - | kitten icat --align left --clear --transfer-mode stream"
  --preview-window 'up:60%:wrap'
  --color='spinner:#F5E0DC,hl:#F38BA8'
  --color='fg:#CDD6F4,header:#F38BA8,info:#a6e3a1,pointer:#F5E0DC'
  --color='marker:#B4BEFE,fg+:#CDD6F4,prompt:#a6e3a1,hl+:#F38BA8'
  --color='selected-bg:#45475A'
  --color='border:#6C7086,label:#CDD6F4'
  --layout reverse
  --cycle
)

eza -G1 -s Name --icons=never "$dir" | fzf "${fzf_args[@]}"
